on:
  workflow_call:

jobs:
  do-nothing:
    name: Build and push container image
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.output.outputs.image-name }}
      image-tag: ${{ steps.output.outputs.image-tag }}
    env:
      IMAGE_NAME: index.docker.io/mohamedmatrouh/test-action
    steps:
      - name: Set release version environment variable
        run: |
          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "release version: ${RELEASE_VERSION}"
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA"
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA" >> $GITHUB_ENV

      - name: pass docker image name and tag to next job
        id: output
        run: |
          echo "image name: ${{env.IMAGE_NAME}}"
          echo "release version: ${{env.RELEASE_VERSION}}"
          echo "::set-output name=image-name::${{env.IMAGE_NAME}}"
          echo "::set-output name=image-tag::${{env.RELEASE_VERSION}}"
    
