name: test and build workflow

on:
  workflow_call:
jobs:
  test-build-code:
    name: Test and Build job
    runs-on:
      - ubuntu-latest
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v3
        id: cache
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('./package.json') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: run test
        run: |
          npm run test -- --coverage

      - name: run build
        run: |
          npm run build

      - name: Upload build artifact for the next job
        if: github.ref == 'refs/heads/prod'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            build
            coverage
