name: Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  build_and_push_image:
    name: Publish to registry
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.output.outputs.image-name }}
      image-tag: ${{ steps.output.outputs.image-tag }}
    env:
      IMAGE_NAME: index.docker.io/mohamedmatrouh/test-action
    steps:
      - name: Set release version environment variable
        run: |
          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "release version: ${RELEASE_VERSION}"
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA"
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA" >> $GITHUB_ENV

      - name: pass docker image name and tag to next job
        id: output
        run: |
          echo "image name: ${{env.IMAGE_NAME}}"
          echo "release version: ${{env.RELEASE_VERSION}}"
          echo "::set-output name=image-name::${{env.IMAGE_NAME}}"
          echo "::set-output name=image-tag::${{env.RELEASE_VERSION}}"

  update-gitops-repo:
    needs: build_and_push_image
    name: update git repository
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/update-gitops-repo.yaml
    with:
      gitops-repo: git@github.com:mohamedmatrouh/gitops-test.git
      kustomization-path: ./dev
      image-name: ${{ needs.build_and_push_image.outputs.image-name }}
      image-tag: ${{ needs.build_and_push_image.outputs.image-tag }}
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}