name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build_and_push_image:
    name: Publish to registry
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.output.outputs.image-name }}
      image-tag: ${{ steps.output.outputs.image-tag }}
    env:
      IMAGE_NAME: index.docker.io/mohamedmatrouh/test-action
    steps:
      - name: Set release version environment variable
        run: |
          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "release version: ${RELEASE_VERSION}"
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA"
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA" >> $GITHUB_ENV

      - name: pass docker image name and tag to next job
        id: output
        run: |
          echo "image name: ${{env.IMAGE_NAME}}"
          echo "release version: ${{env.RELEASE_VERSION}}"
          echo "::set-output name=image-name::${{env.IMAGE_NAME}}"
          echo "::set-output name=image-tag::${{env.RELEASE_VERSION}}"

  update-gitops-repo:
    needs: build_and_push_image
    name: update git repository
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{needs.build_and_push_image.outputs.image-name}}
      IMAGE_TAG: ${{needs.build_and_push_image.outputs.image-tag}}
    steps:
      - run: echo "needs.build_and_push_image.outputs.image-tag ${{env.IMAGE_NAME}}"
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: '3.9.4'

      - run: echo "needs.build_and_push_image.outputs:${{needs.build_and_push_image.outputs}}"
      - name: update image campus home
        run: |
          git clone git@github.com:mohamedmatrouh/gitops-test.git /tmp/gitops-test
          cd /tmp/gitops-test/dev
          kustomize edit set image $IMAGE_NAME=$IMAGE_NAME:$IMAGE_TAG
          cd /tmp//gitops-test
          git version
          git status
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "[GitHub Action] Set $GITHUB_BASE_REF frontend image tag to $IMAGE_TAG"
          git push
          cd /tmp
          rm -rf /gitops-test
