name: Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  build_and_push_image:
    name: Publish to registry
    uses: ./.github/workflows/cd-workflow.yaml

  update-gitops-repo:
    needs: build_and_push_image

    name: update git repository

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    uses: ./.github/workflows/update-gitops-repo.yaml

    with:
      gitops-repo: git@github.com:mohamedmatrouh/gitops-test.git
      kustomization-path: ./dev
      image-name: ${{ needs.build_and_push_image.outputs.image-name }}
      image-tag: ${{ needs.build_and_push_image.outputs.image-tag }}
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}