name: Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-test:
    uses: ./.github/workflows/npm.yaml

  build-docker-image:
    name: Build docker image

    runs-on: ubuntu-latest

    needs: test-build-code

    outputs:
      image-name: ${{ steps.output.outputs.image-name }}
      image-tag: ${{ steps.output.outputs.image-tag }}

    env:
      REGISTRY_URL: index.docker.io
      REGISTRY_REPOSITORY: mohamedmatrouh/test-action
      REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: mohamedmatrouh
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Log in to the container registry
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ env.REGISTRY_URL }}
#          username: mohamedmatrouh
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build

      - name: Set release version environment variable
        run: |
          RELEASE_VERSION=0.0.1.SNAPSHOT
          echo "RELEASE_VERSION=$RELEASE_VERSION-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build docker image
        run: |
          docker image build \
          -f Dockerfile \
          -t ${REGISTRY_REPOSITORY} \
          .

      - name: Tag docker image
        run: |
          docker image tag \
          ${REGISTRY_REPOSITORY} \
          ${REGISTRY_URL}/${REGISTRY_REPOSITORY}:${RELEASE_VERSION}

      - name: Push docker image
        run: docker push ${REGISTRY_URL}/${REGISTRY_REPOSITORY}:${RELEASE_VERSION}

      - name: pass docker image name and tag to next job
        id: output
        run: |
          echo "::set-output name=image-name::${REGISTRY_URL}/${REGISTRY_REPOSITORY}"
          echo "::set-output name=image-tag::${RELEASE_VERSION}"

  update-gitops-repo:
    needs: build-docker-image
    name: update git repository
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{needs.build-docker-image.outputs.image-name}}
      IMAGE_TAG: ${{needs.build-docker-image.outputs.image-tag}}
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: '3.9.4'

      - run: git clone git@github.com:mohamedmatrouh/gitops-test.git /tmp/gitops-test

      - name: update image campus home
        run: |
          cd /tmp/gitops-test/dev
          kustomize edit set image $IMAGE_NAME=$IMAGE_NAME:$IMAGE_TAG
          cd /tmp/gitops-test/
          git version
          git status
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "[GitHub Action] Set $GITHUB_BASE_REF frontend image tag to $IMAGE_TAG"
          git push
          cd ..
          rm -rf gitops-test