on:
  workflow_call:
    inputs:
      gitops-repo:
        required: true
        type: string
      kustomization-path:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      DEPLOY_KEY:
        required: true

jobs:
  update-gitops-repo:
    name: update git repository
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: '3.9.4'

      - name: clone the repository
        run: git clone "${{ inputs.gitops-repo }}" /tmp/temp-folder

      - name: update image
        run: |
          cd /tmp/temp-folder/${{ inputs.kustomization-path }}
          kustomize edit set image ${{ inputs.image-name }}=${{ inputs.image-name }}:${{ inputs.image-tag }}
      - name: push chnages
        run: |
          cd /tmp/temp-folder
          git version
          git status
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "[GitHub Action] Set $GITHUB_BASE_REF frontend image tag to ${{ inputs.image-tag }}"
          git push
      - name: clean up
        run:
          cd /tmp
          rm -rf /tmp/temp-folder
